### ISSUE TITLE
trace方便开源吗？

### ISSUE THREAD

**Issue by xuboshi1221** [hkust-spark/hairpin#1]
孟博士你好！看到你主页发表的NSDI24 Hairpin这篇文章感觉非常有趣和前沿，请问代码中用到的相关trace文件方便提供吗？非常感谢，盼复!

**Comment by mengzili** [comment]
你好！非常抱歉由于一些原因，paper中的整体的trace数据集暂时没办法提供。我们在代码里面提供了一个sample的trace可以用来运行。

https://github.com/hkust-spark/ns3-sparkrtc/blob/f7025dffd2f3ef1bfeeb6c142601833ca98cec4d/examples/sample.tr

我们计划重新采集一些新的数据集，如果有新的进展我们会随时update。谢谢！
